[package]
name = "xec_package"
version = "0.0.1"
authors = ["eCash]
license = "Apache-2.0"

[addresses]
xec = "0x92baf7a2dcb487f54a3f8f0f7ffee6dd07517f1b94b05e89355995a371b7df35"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", rev = "main" }

[dev-addresses]
Std = "0x1"
