[package]
name = "move-vm-runtime"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Core Move execution logic"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bcs.workspace = true
better_any.workspace = true
bumpalo.workspace = true
fail.workspace = true
hex.workspace = true
lasso.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
serde.workspace = true
sha2.workspace = true
sha3.workspace = true
smallvec.workspace = true
tracing.workspace = true

# referred to via path for execution versioning
move-bytecode-verifier = { path = "../move-bytecode-verifier" }
move-core-types.workspace = true
move-vm-config.workspace = true
move-binary-format.workspace = true
move-vm-profiler.workspace = true
petgraph.workspace = true

[dev-dependencies]
anyhow.workspace = true
hex.workspace = true
proptest.workspace = true
move-ir-compiler.workspace = true
move-ir-to-bytecode.workspace = true
move-compiler.workspace = true
memory-stats.workspace = true
tempfile.workspace = true
move-stdlib.workspace = true
move-proc-macros.workspace = true

[features]
default = []
fuzzing = []
failpoints = ["fail/failpoints"]
# Enable tracing and debugging also for release builds. By default, it is only enabled for debug builds.
debugging = []
testing = []
lazy_natives = []
tiered-gas = []
gas-profiler = [
    "move-vm-config/gas-profiler",
    "move-vm-profiler/gas-profiler",
]
